spring:
  application:
    name: x-payment-adapter-app
  profiles:
    active: kafka,rabbitmq

app:
  x-payment-api:
    client:
      url: ${APP_X_PAYMENT_API_CLIENT_URL:http://xpayment-api:8080}
      username: paymentAgentIprody
      password: iprodyTestPassword0123
      account: paymentAgentIprodyApiToken

management:
  tracing:
    sampling:
      probability: 1.0 # 100% для отладки; в продакшн должен быть меньше
    propagation:
      type: w3c,b3 # чтобы понимать и traceparent, и b3
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans

logging:
  level:
    root: INFO
    org.springframework.jdbc.core: ERROR
    org.springframework.web: WARN
    org.springframework.data: WARN
    org.springframework.amqp: DEBUG
